# Generated by Django 4.1.1 on 2022-09-26 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='image',
            new_name='preview',
        ),
        migrations.AddField(
            model_name='image',
            name='New',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.news'),
        ),
        migrations.AlterField(
            model_name='image',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
        ),
    ]
