# Generated by Django 4.1.1 on 2022-09-26 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_category_description_alter_image_new_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='New',
            new_name='post',
        ),
    ]
