# Generated by Django 4.1.1 on 2022-09-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
